resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: adimgit1
      path: adim1/pipelines-simple-steps
pipelines:
  - name: pipeline_hello_world
    configuration:
      environmentVariables:
        readOnly:
          MY_MESSAGE: '"Hello World!"'
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - echo $MY_MESSAGE
            - echo “running CI for master”
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: myAppRepo
        execution:
          onExecute:
            - echo "This is step two"
            - echo “running CI for master Second step!”
